In [12]:
import numpy as np

In [13]:
w = np.random.random(5)
print(w)

[0.02074481 0.73598228 0.63285031 0.41245254 0.01538799]


In [14]:
x = [0.1,0.4,0.6,0.7,-0.1]
output_lbl = 1
counter = 0
total = 0
while total <= 1:
    
    
    for i in range (len(w)):
        w[i] = w[i]+x[i]
    print(w)
    counter = counter + 1
    total =np.dot(w,x)
    print(total)
    
    
    

print("Loops Required : ",counter)

[ 0.12074481  1.13598228  1.23285031  1.11245254 -0.08461201]
1.9933555609586164
Loops Required :  1


In [15]:
x = [0.1,0.4,0.6,0.7,-0.1]
output_lbl = 1
counter = 0
total = 0
while total < 1:
    
    
    for i in range (len(w)):
        w[i] = w[i]+x[i]
    print(w)
    counter = counter + 1
    total =0.01*np.dot(w,x)
    print(total)
print("Loops Required : ",counter)
    

[ 0.22074481  1.53598228  1.83285031  1.81245254 -0.18461201]
0.03023355560958616
[ 0.32074481  1.93598228  2.43285031  2.51245254 -0.28461201]
0.040533555609586165
[ 0.42074481  2.33598228  3.03285031  3.21245254 -0.38461201]
0.05083355560958617
[ 0.52074481  2.73598228  3.63285031  3.91245254 -0.48461201]
0.06113355560958617
[ 0.62074481  3.13598228  4.23285031  4.61245254 -0.58461201]
0.07143355560958617
[ 0.72074481  3.53598228  4.83285031  5.31245254 -0.68461201]
0.08173355560958617
[ 0.82074481  3.93598228  5.43285031  6.01245254 -0.78461201]
0.09203355560958616
[ 0.92074481  4.33598228  6.03285031  6.71245254 -0.88461201]
0.10233355560958617
[ 1.02074481  4.73598228  6.63285031  7.41245254 -0.98461201]
0.11263355560958616
[ 1.12074481  5.13598228  7.23285031  8.11245254 -1.08461201]
0.12293355560958615
[ 1.22074481  5.53598228  7.83285031  8.81245254 -1.18461201]
0.13323355560958616
[ 1.32074481  5.93598228  8.43285031  9.51245254 -1.28461201]
0.14353355560958614
[ 1.42074481  6

In [16]:
x = [0.1,0.4,0.6,0.7,-0.1]
output_lbl = 1
counter = 0
total = 0
while total >1:
        for i in range (len(w)):
            w[i] = w[1]-w[i]
            print(w)
            counter = counter + 1
            total =0.01*np.dot(w,x)
            print(total)
print("Loops Required : ",counter)            

Loops Required :  0
